# Generated by Django 5.2.4 on 2025-10-12 13:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interviewquestion_interviewanswer_interviewsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('total_modules', models.PositiveIntegerField(default=0)),
                ('completed_modules', models.JSONField(default=list)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course_name')},
            },
        ),
    ]
