# Generated by Django 5.2.4 on 2025-10-14 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_courseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='daily_count', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('learning_days_streak', models.IntegerField(default=0, verbose_name='Current Learning Streak (Days)')),
                ('count_last_date', models.DateField(blank=True, null=True, verbose_name='Last Streak Update Date')),
                ('month_wise_count', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Knowledge Point Title')),
                ('content', models.TextField(verbose_name='Detailed Description')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Last Content Update')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resume_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('performance', models.CharField(blank=True, choices=[('poor', 'Poor'), ('average', 'Average'), ('good', 'Good')], max_length=10, null=True, verbose_name='Resume Performance')),
                ('resume_count', models.IntegerField(default=1, verbose_name='Current Learning Streak (Days)')),
                ('last_parsed_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Analysis Date')),
            ],
        ),
    ]
