# Generated by Django 5.2.4 on 2025-10-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
