# Generated by Django 5.2.4 on 2026-02-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_profile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
