# Generated by Django 5.2.9 on 2026-02-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_interviewanswer_feedback_interviewanswer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inventory',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
