# Generated by Django 5.2.4 on 2026-03-08 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_interviewmatch_interviewqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('module_id', models.CharField(max_length=50)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer_index', models.IntegerField()),
                ('base_difficulty', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quizquestionbank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuizProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_model_trained', models.BooleanField(default=False)),
                ('total_responses', models.IntegerField(default=0)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
