# Generated by Django 5.2.9 on 2026-03-08 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_quizquestionbank_quizresponse_userquizprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=50)),
                ('question_text', models.TextField()),
                ('question_hash', models.CharField(db_index=True, max_length=255)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField()),
                ('confidence_rating', models.IntegerField(blank=True, null=True)),
                ('predicted_probability', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserModelStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=50)),
                ('model_data', models.BinaryField()),
                ('last_trained_at', models.DateTimeField(auto_now=True)),
                ('training_samples_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module_id')},
            },
        ),
        migrations.CreateModel(
            name='UserModuleStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=50)),
                ('total_answered', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('last_quiz_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module_id')},
            },
        ),
    ]
